## Default values for eric-sec-sip-tls-crd.
## This is a YAML-formatted file.
## Declare variables to be passed into your templates.

#global:
#  security:
#    policyBinding:
#      create: false
#    policyReferenceMap:
#      default-restricted-security-policy: default-restricted-security-policy
  ## pullSecret, the secret resource name used for authenticating towards docker registry where images are pulled
  #pullSecret:
  #registry:
    ## Docker registry url
    #url: armdocker.rnd.ericsson.se
    ## imagePullPolicy, desired policy under which condition the images are pulled from registry
    #imagePullPolicy: IfNotPresent
  ## fsGroup, to set up the proper gid value for accessing mounted persistent data (default is 10000 if not defined)
  #fsGroup:
    ## 'manual' to enforce a specific value (this has the highest precedence)
    #manual: 15000
    ## 'namespace' to use the value defined for the namespace set by the cluster admin (second highest precedence)
    #namespace: true

imageCredentials:
  repoPath: proj-common-assets-cd/security
  ## pullSecret, the secret resource name used for authenticating towards docker registry where images are pulled
  ## overrides the global value when set
  #pullSecret: null
  registry:
    ## url, service specific Docker registry url, overrides the global value when set
    url: null
    ## imagePullPolicy, service specific policy, overrides the global value when set
    #imagePullPolicy: null

images:
  crdjob:
    name: eric-sec-sip-tls-crd-job
    tag: 2.2.0-30

## Possible values: debug, info, error
logLevel: info
