{{ if (not (.Capabilities.APIVersions.Has "com.ericsson.sec.tls/v1alpha1")) }}

# CertificateAuthority CRD deployment is excluded from deployment
# if it is already installed manually to the cluster.
# Note that due to previous manual installation, this resource cannot be
# maintained by helm but must be removed manually.
# Removing CRD will result removal of all client CR's as well.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificateauthorities.com.ericsson.sec.tls
  labels:
    {{- include "eric-sec-sip-tls-crd.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-sec-sip-tls-crd.product-info" . | nindent 4 }}
    "helm.sh/resource-policy": keep
spec:
  group: com.ericsson.sec.tls
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: certificateauthorities
    singular: certificateauthority
    kind: CertificateAuthority
    shortNames:
    - certauthority
    - ca
  {{- if (semverCompare ">=1.15" .Capabilities.KubeVersion.GitVersion) }}
  preserveUnknownFields: false
  {{- end }}
  validation:
    openAPIV3Schema:
      type: object
      description: CertificateAuthority is used to request user specific CA from SIP-TLS.
      properties:
        spec:
          required:
          - generated-secret-name
          - common-name
          type: object
          description: Spec defines the properties of the certificate and private key.
          properties:
            generated-secret-name:
              type: string
              pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
            common-name:
              type: string
  additionalPrinterColumns:
    - name: CN
      type: string
      description: The requested CA certificate common name.
      JSONPath: .spec.common-name
    - name: Secret
      type: string
      description: The Kubernetes secret where the CA certificate is stored.
      JSONPath: .spec.generated-secret-name
{{- end }}
