{{ if (not (.Capabilities.APIVersions.Has "com.ericsson.sec.tls/v1alpha1")) }}

# ClientCertificate CRD deployment is excluded from deployment
# if it is already installed manually to the cluster.
# Note that due to previous manual installation, this resource cannot be
# maintained by helm but must be removed manually.
# Removing CRD will result removal of all client CR's as well.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clientcertificates.com.ericsson.sec.tls
  labels:
    {{- include "eric-sec-sip-tls-crd.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-sec-sip-tls-crd.product-info" . | nindent 4 }}
    "helm.sh/resource-policy": keep
spec:
  group: com.ericsson.sec.tls
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: clientcertificates
    singular: clientcertificate
    kind: ClientCertificate
    shortNames:
    - clientcert
    - clientcerts
  {{- if (semverCompare ">=1.15" .Capabilities.KubeVersion.GitVersion) }}
  preserveUnknownFields: false
  {{- end }}
  validation:
    openAPIV3Schema:
      type: object
      description: ClientCertificate is used to request a client certificate and private key from SIP-TLS.
      properties:
        spec:
          required:
          - generated-secret-name
          - common-name
          - issuer-ref
          type: object
          description: Spec defines the properties of the certificate and private key.
          properties:
            generated-secret-name:
              type: string
              # Use the same regex as used by Kubernetes API Server
              pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
            common-name:
              type: string
              # Disallow underscores and whitespace
              pattern: '^[^_\s]+$'
            issuer-ref:
              type: string
              # Disallow underscores and whitespace
              pattern: '^[^_\s]+$'
            additional-sans:
              type: array
              items:
                type: string
                # In the form of <prefix>:<suffix>
                # Supported prefixes: 'DNS:'
                # Disallow underscores and whitespace
                pattern: '^DNS:[^_\s]+$'
            override-ttl:
              type: integer
              minimum: 180
  additionalPrinterColumns:
    - name: CN
      type: string
      description: The requested certificate common name.
      JSONPath: .spec.common-name
    - name: Secret
      type: string
      description: The Kubernetes secret where the certificate and key are stored.
      JSONPath: .spec.generated-secret-name
{{- end }}
