apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-sec-sip-tls-crd.name" . }}-config
  labels:
    {{- include "eric-sec-sip-tls-crd.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-sec-sip-tls-crd.product-info" . | nindent 4 }}
data:
  check_crds.bash: |
    {{- tpl (.Files.Get "files/check_crds.bash") . | nindent 4 }}
  logger.bash: |
    {{- tpl (.Files.Get "files/logger.bash") . | nindent 4 }}
  crds.bash: |
    {{- tpl (.Files.Get "files/crds.bash") . | nindent 4 }}
