apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: internalusercas.siptls.sec.ericsson.com
  labels:
    {{- include "eric-sec-sip-tls-crd.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-sec-sip-tls-crd.product-info" . | nindent 4 }}
    "helm.sh/resource-policy": keep
spec:
  group: siptls.sec.ericsson.com
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: internalusercas
    singular: internaluserca
    kind: InternalUserCA
    shortNames:
      - intuserca
      - intusercas
  {{- if (semverCompare ">=1.15" .Capabilities.KubeVersion.GitVersion) }}
  preserveUnknownFields: false
  {{- end }}
  validation:
    openAPIV3Schema:
      type: object
      description: InternalUserCA is used to request a CA certificate from SIP-TLS.
      properties:
        spec:
          required:
            - kubernetes
            - certificate
          type: object
          description: Spec defines the properties of the CA certificate.
          properties:

            kubernetes:
              type: object
              description: Defines properties related to the storage of the certificate and private key in Kubernetes.
              required:
                - generatedSecretName
              properties:
                generatedSecretName:
                  type: string
                  description: The secret where the CA certificate is stored. The same secret should not be used for
                               multiple purposes.
                  # Use the same regex as used by Kubernetes API Server
                  pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'

                certificateName:
                  type: string
                  description: The YAML key name of the CA certificate in the secret. If not given, 'ca.pem' is used.
                  # Disallow whitespace
                  pattern: '^[^\s]+$'

            certificate:
              type: object
              description: Defines properties related to the content of the CA certificate.
              required:
                - subject
              properties:
                subject:
                  type: object
                  description: Properties related to X.509 'Subject' field.
                  required:
                    - cn
                  properties:
                    cn:
                      type: string
                      description: The Subject Common Name (CN) of the CA certificate.
                      # Don't allow empty string
                      minLength: 1
  additionalPrinterColumns:
    - name: CN
      type: string
      description: The requested CA certificate common name.
      JSONPath: .spec.certificate.subject.cn
    - name: Secret
      type: string
      description: The Kubernetes secret where the CA certificate is stored.
      JSONPath: .spec.kubernetes.generatedSecretName
